shared: &shared
  domain: "mydomain.net"
  authentication: "login"
  user_name:  "tonyxpk@gmail.com"
  password:  "zqnkhizklfqdgmmn"
  address: "tonyxpk@gmail.com"
development:
  <<: *shared

production:
  <<: *shared
  
